apiVersion: v1
kind: Service
metadata:
   name: dns-svc
spec:
   type: NodePort
   ports:
    - port: 80
      targetPort: 80
      nodePort: 32000
      protocol: TCP
   selector:
      run-application.conf/app: dot-app
      run-application.conf/data: dot-data
---
apiVersion: v1
kind: Pod
metadata:
   name: dns-mob
   labels:
      run-application.conf/app: dot-app
      run-application.conf/data: dot-data
spec:
  volumes:
     - name: fo
       configMap:
         name: conf-data
  containers:
    - image: nginx:1.16.1
      name: nginx
      ports:
       - containerPort: 80
      env:
       - name: HOST_DNS_SERVER
         valueFrom:
            configMapKeyRef:
               name: conf-data
               key: HOST_DNS_SERVER
       - name: HOST_IP_ADDRESS
         valueFrom:
            configMapKeyRef:
               name: conf-data
               key: HOST_IP_ADDRESS
      volumeMounts:
        - name: fo
          mountPath: /tmp/ 
